- name: Update and upgrade Arch system
  pacman:
    update_cache: true
    upgrade: true
- name: Install pacman packages
  pacman:
    name: '{{ item }}'
    state: present
  loop:
    - git
    - base-devel
    - zsh
    - vim
    - cronie
    - dns-over-https
    - tmux
    - trivy
    - xclip
    - adobe-source-code-pro-fonts
    - alacritty
    - android-tools
    - ansible
    - arandr
    - archlinux-keyring
    - aria2
    - ark
    - bash-completion
    - bat
    - cmus
    - containerd
    - copyq
    - delve
    - docker
    - dunst
    - eza
    - fd
    - feh
    - ffmpeg
    - ffmpegthumbnailer
    - flameshot
    - fzf
    - gnome-keyring
    - go
    - go-tools
    - go-yq
    - grep
    - helm
    - htop
    - hugo
    - jq
    - keepassxc
    - keychain
    - kubectl
    - kustomize
    - lua
    - mousepad
    - mpv
    - nmap
    - pavucontrol
    - qbittorrent
    - ripgrep
    - sheldon
    - shellcheck
    - nomacs
    - playerctl
    - terraform
    - tesseract
    - tesseract-data-eng
    - tesseract-data-osd
    - the_silver_searcher
    - thunar
    - tmux
    - unclutter
    - unrar
    - unzip
    - wget
    - zathura
    - zoxide
    - stow
- name: Create the `aur_builder` user
  become: true
  ansible.builtin.user:
    name: aur_builder
    create_home: true
    group: wheel
- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: true
    mode: 0644
    validate: 'visudo -cf %s'
- name: Install AUR packages
  kewlfft.aur.aur:
    name: '{{ item}}'
    state: present
  become: true
  become_user: aur_builder
  loop:
    - anki-bin
    - dropbox
    - imagewriter
    - sioyek
    - ueberzugpp
    - ulauncher
    - appimagelauncher-bin
    - atuin
    - doppler-cli-bin
    - epub-thumbnailer-git
    - picom-arian8j2-git
    - ffmpeg-audio-thumbnailer
    - ttf-font-awesome-5
    - git-delta
    - github-cli
    - dracula-gtk-theme
    - catppuccin-cursors-mocha
    - epapirus-icon-theme-git
    - papirus-icon-theme-git
    - gitleaks
    - grype-bin
    - hadolint-bin
    - i3status-rust
    - jnv
    - k9s
    - keyd
    - localsend-bin
    - mods-bin
    - floorp-bin
    - microsoft-edge-stable-bin
    - oh-my-posh-bin
    - oha
    - ripgrep-all
    - spotify
    - spotify-adblock-git
    - thunar-archive-plugin-git
    - tumbler-devel
    - tumbler-extra-thumbnailers
    - vhs
    - visual-studio-code-bin
    - yazi
    - fixjson
    - sql-formatter
    - golangci-lint-bin
    - yamlfmt
    - ttf-jetbrains-mono-nerd
    - ttf-sourcecodepro-nerd
    - ttf-0xproto-nerd
    - ttf-atkinson-hyperlegible
    - ansible-lint
    - tmux-plugin-manager
