shell = "zsh"
[plugins.syntax-highlighting]
github = 'zdharma-continuum/fast-syntax-highlighting'

[plugins.completions]
github = 'zsh-users/zsh-completions'

[plugins.autosuggestions]
github = 'zsh-users/zsh-autosuggestions'

[plugins.vim-mod]
github = 'jeffreytse/zsh-vi-mode'

[plugins.you-should-use]
github = 'MichaelAquilina/zsh-you-should-use'

[plugins.fzf-tab]
github = 'Aloxaf/fzf-tab'

[plugins.fzf-tab-source]
github = 'Freed-Wu/fzf-tab-source'

[plugins.auto-notify]
github = 'MichaelAquilina/zsh-auto-notify'

[plugins.expand]
github = 'MenkeTechnologies/zsh-expand'