#                 ╭─────────────────────────────────────────────╮
#                 │ Written by @Fadynagh from http://fadyio.com │
#                 │             Email:me@fadyio.com             │
#                 │               Github: @Fadyio               │
#                 ╰─────────────────────────────────────────────╯

theme = "gruvbox-dark"
icons = "material-nf"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0


[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}"
format_swap = "{swap_used}/{swap_total}"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1
format = "{utilization}"

[[block]]
block = "net"
device = "eno1"
format = "{speed_down;K*b} {speed_up;K*b}"
interval = 5

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %I:%M %p"
