## where to store your database, default is your system data directory
db_path = "~/.history.db"

## date format used, either "us" or "uk"
dialect = "us"

## enable or disable automatic sync
auto_sync = true

## enable or disable automatic update checks
update_check = true

show_help = false

## address of the sync server
sync_address = "https://api.atuin.sh"

## how often to sync history. note that this is only triggered when a command
sync_frequency = "1h"

## which search mode to use
## possible values: prefix, fulltext, fuzzy, skim
search_mode = "fuzzy"

## which filter mode to use
## possible values: global, host, session, directory
filter_mode = "global"

## which style to use
## possible values: auto, full, compact
style = "compact"

keymap_mode = "vim-normal"

## the maximum number of lines the interface should take up
## set it to 0 to always go full screen
inline_height = 16

## what to do when the escape key is pressed when searching
## possible values: return-original, return-query
exit_mode = "return-original"

## prevent commands matching any of these regexes from being written to history.
## Note that these regular expressions are unanchored, i.e. if they don't start
## with ^ or end with $, they'll match anywhere in the command.
## For details on the supported regular expression syntax, see
## https://docs.rs/regex/latest/regex/#syntax
history_filter = [
  "^gh copilot suggest",
  "^mods",
  "^doppler",

]
