import = [
  "/usr/lib/node_modules/alacritty-themes/themes/Catppuccin-Mocha.toml"
]
live_config_reload = true

[font]
size = 13

  [font.normal]
  family = "JetBrainsMono Nerd Font"
  style = "Regular"

[window]
opacity = 0.9
